### ISSUE TITLE
symbols.py _characters

### ISSUE THREAD

**Issue by shakingWaves** [cnlinxi/tacotron2#1]
train_text_files = glob.glob(os.path.join('../../female_golden_v2', '*.corpus'))
if train_text_files and AUTO_DETECT_SYMBOLS:
    _characters = set()
    for file in train_text_files:
        with open(file,'rb') as fin:
            for line in fin:
                line=line.decode().split('|')[1]
                _characters=_characters.union(line)
else:
    _characters = 'abcdefghijklmnopqrstuvwxyz12345；，。、？“”，：！-《》（） '

这里_characters的内容，是不是和
_characters = ['a1', 'a2', 'a3', 'a4', 'a5', 'ai1', 'ai2', 'ai3', 'ai4', 'ai5', 'an1', 'an2', 'an3', 'an4', 'an5', 'ang1', 'ang2', 'ang3', 'ang4', 'ang5', 'ao1', 'ao2', 'ao3', 'ao4', 'ao5', 'ba1', 'ba2', 'ba3', 'ba4', 'ba5', 'bai1', 'bai2', 'bai3', 'bai4', 'bai5', 'ban1', 'ban2', 'ban3', 'ban4', 'ban5', 'bang1', 'bang2', 'bang3', 'bang4', 'bang5', 'bao1', 'bao2', 'bao3', 'bao4', 'bao5', 'bei1', 'bei2', 'bei3', 'bei4', 'bei5', 'ben1', 'ben2', 'ben3', 'ben4', 'ben5', 'beng1', 'beng2', 'beng3', 'beng4', 'beng5', 'bi1', 'bi2', 'bi3', 'bi4', 'bi5', 'bian1', 'bian2', 'bian3', 'bian4', 'bian5', 'biao1', 'biao2', 'biao3', 'biao4', 'biao5', 'bie1', 'bie2', 'bie3', 'bie4', 'bie5', 'bin1', 'bin2', 'bin3', 'bin4', 'bin5', 'bing1', 'bing2', 'bing3', 'bing4', 'bing5', 'bo1', 'bo2', 'bo3', 'bo4', 'bo5', 'bu1', 'bu2', 'bu3', 'bu4', 'bu5', 'ca1', 'ca2', 'ca3', 'ca4', 'ca5', 'cai1', 'cai2', 'cai3', 'cai4', 'cai5', 'can1', 'can2', 'can3', 'can4', 'can5', 'cang1', 'cang2', 'cang3', 'cang4', 'cang5', 'cao1', 'cao2', 'cao3', 'cao4', 'cao5', 'ce1', 'ce2', 'ce3', 'ce4', 'ce5', 'cen1', 'cen2', 'cen3', 'cen4', 'cen5', 'ceng1', 'ceng2', 'ceng3', 'ceng4', 'ceng5', 'cha1', 'cha2', 'cha3', 'cha4', 'cha5', 'chai1', 'chai2', 'chai3', 'chai4', 'chai5', 'chan1', 'chan2', 'chan3', 'chan4', 'chan5', 'chang1', 'chang2', 'chang3', 'chang4', 'chang5', 'chao1', 'chao2', 'chao3', 'chao4', 'chao5', 'che1', 'che2', 'che3', 'che4', 'che5', 'chen1', 'chen2', 'chen3', 'chen4', 'chen5', 'cheng1', 'cheng2', 'cheng3', 'cheng4', 'cheng5', 'chiii1', 'chiii2', 'chiii3', 'chiii4', 'chiii5', 'chong1', 'chong2', 'chong3', 'chong4', 'chong5', 'chou1', 'chou2', 'chou3', 'chou4', 'chou5', 'chu1', 'chu2', 'chu3', 'chu4', 'chu5', 'chuai1', 'chuai2', 'chuai3', 'chuai4', 'chuai5', 'chuan1', 'chuan2', 'chuan3', 'chuan4', 'chuan5', 'chuang1', 'chuang2', 'chuang3', 'chuang4', 'chuang5', 'chuei1', 'chuei2', 'chuei3', 'chuei4', 'chuei5', 'chuen1', 'chuen2', 'chuen3', 'chuen4', 'chuen5', 'chuo1', 'chuo2', 'chuo3', 'chuo4', 'chuo5', 'cii1', 'cii2', 'cii3', 'cii4', 'cii5', 'cong1', 'cong2', 'cong3', 'cong4', 'cong5', 'cou1', 'cou2', 'cou3', 'cou4', 'cou5', 'cu1', 'cu2', 'cu3', 'cu4', 'cu5', 'cuan1', 'cuan2', 'cuan3', 'cuan4', 'cuan5', 'cuei1', 'cuei2', 'cuei3', 'cuei4', 'cuei5', 'cuen1', 'cuen2', 'cuen3', 'cuen4', 'cuen5', 'cuo1', 'cuo2', 'cuo3', 'cuo4', 'cuo5', 'da1', 'da2', 'da3', 'da4', 'da5', 'dai1', 'dai2', 'dai3', 'dai4', 'dai5', 'dan1', 'dan2', 'dan3', 'dan4', 'dan5', 'dang1', 'dang2', 'dang3', 'dang4', 'dang5', 'dao1', 'dao2', 'dao3', 'dao4', 'dao5', 'de1', 'de2', 'de3', 'de4', 'de5', 'dei1', 'dei2', 'dei3', 'dei4', 'dei5', 'den1', 'den2', 'den3', 'den4', 'den5', 'deng1', 'deng2', 'deng3', 'deng4', 'deng5', 'di1', 'di2', 'di3', 'di4', 'di5', 'dia1', 'dia2', 'dia3', 'dia4', 'dia5', 'dian1', 'dian2', 'dian3', 'dian4', 'dian5', 'diao1', 'diao2', 'diao3', 'diao4', 'diao5', 'die1', 'die2', 'die3', 'die4', 'die5', 'ding1', 'ding2', 'ding3', 'ding4', 'ding5', 'diou1', 'diou2', 'diou3', 'diou4', 'diou5', 'dong1', 'dong2', 'dong3', 'dong4', 'dong5', 'dou1', 'dou2', 'dou3', 'dou4', 'dou5', 'du1', 'du2', 'du3', 'du4', 'du5', 'duan1', 'duan2', 'duan3', 'duan4', 'duan5', 'duei1', 'duei2', 'duei3', 'duei4', 'duei5', 'duen1', 'duen2', 'duen3', 'duen4', 'duen5', 'duo1', 'duo2', 'duo3', 'duo4', 'duo5', 'e1', 'e2', 'e3', 'e4', 'e5', 'ei1', 'ei2', 'ei3', 'ei4', 'ei5', 'en1', 'en2', 'en3', 'en4', 'en5', 'eng1', 'eng2', 'eng3', 'eng4', 'eng5', 'er1', 'er2', 'er3', 'er4', 'er5', 'er1', 'er2', 'er3', 'er4', 'er5', 'fa1', 'fa2', 'fa3', 'fa4', 'fa5', 'fan1', 'fan2', 'fan3', 'fan4', 'fan5', 'fang1', 'fang2', 'fang3', 'fang4', 'fang5', 'fei1', 'fei2', 'fei3', 'fei4', 'fei5', 'fen1', 'fen2', 'fen3', 'fen4', 'fen5', 'feng1', 'feng2', 'feng3', 'feng4', 'feng5', 'fo1', 'fo2', 'fo3', 'fo4', 'fo5', 'fou1', 'fou2', 'fou3', 'fou4', 'fou5', 'fu1', 'fu2', 'fu3', 'fu4', 'fu5', 'ga1', 'ga2', 'ga3', 'ga4', 'ga5', 'gai1', 'gai2', 'gai3', 'gai4', 'gai5', 'gan1', 'gan2', 'gan3', 'gan4', 'gan5', 'gang1', 'gang2', 'gang3', 'gang4', 'gang5', 'gao1', 'gao2', 'gao3', 'gao4', 'gao5', 'ge1', 'ge2', 'ge3', 'ge4', 'ge5', 'gei1', 'gei2', 'gei3', 'gei4', 'gei5', 'gen1', 'gen2', 'gen3', 'gen4', 'gen5', 'geng1', 'geng2', 'geng3', 'geng4', 'geng5', 'gong1', 'gong2', 'gong3', 'gong4', 'gong5', 'gou1', 'gou2', 'gou3', 'gou4', 'gou5', 'gu1', 'gu2', 'gu3', 'gu4', 'gu5', 'gua1', 'gua2', 'gua3', 'gua4', 'gua5', 'guai1', 'guai2', 'guai3', 'guai4', 'guai5', 'guan1', 'guan2', 'guan3', 'guan4', 'guan5', 'guang1', 'guang2', 'guang3', 'guang4', 'guang5', 'guei1', 'guei2', 'guei3', 'guei4', 'guei5', 'guen1', 'guen2', 'guen3', 'guen4', 'guen5', 'guo1', 'guo2', 'guo3', 'guo4', 'guo5', 'ha1', 'ha2', 'ha3', 'ha4', 'ha5', 'hai1', 'hai2', 'hai3', 'hai4', 'hai5', 'han1', 'han2', 'han3', 'han4', 'han5', 'hang1', 'hang2', 'hang3', 'hang4', 'hang5', 'hao1', 'hao2', 'hao3', 'hao4', 'hao5', 'he1', 'he2', 'he3', 'he4', 'he5', 'hei1', 'hei2', 'hei3', 'hei4', 'hei5', 'hen1', 'hen2', 'hen3', 'hen4', 'hen5', 'heng1', 'heng2', 'heng3', 'heng4', 'heng5', 'hong1', 'hong2', 'hong3', 'hong4', 'hong5', 'hou1', 'hou2', 'hou3', 'hou4', 'hou5', 'hu1', 'hu2', 'hu3', 'hu4', 'hu5', 'hua1', 'hua2', 'hua3', 'hua4', 'hua5', 'huai1', 'huai2', 'huai3', 'huai4', 'huai5', 'huan1', 'huan2', 'huan3', 'huan4', 'huan5', 'huang1', 'huang2', 'huang3', 'huang4', 'huang5', 'huei1', 'huei2', 'huei3', 'huei4', 'huei5', 'huen1', 'huen2', 'huen3', 'huen4', 'huen5', 'huo1', 'huo2', 'huo3', 'huo4', 'huo5', 'ji1', 'ji2', 'ji3', 'ji4', 'ji5', 'jia1', 'jia2', 'jia3', 'jia4', 'jia5', 'jian1', 'jian2', 'jian3', 'jian4', 'jian5', 'jiang1', 'jiang2', 'jiang3', 'jiang4', 'jiang5', 'jiao1', 'jiao2', 'jiao3', 'jiao4', 'jiao5', 'jie1', 'jie2', 'jie3', 'jie4', 'jie5', 'jin1', 'jin2', 'jin3', 'jin4', 'jin5', 'jing1', 'jing2', 'jing3', 'jing4', 'jing5', 'jiong1', 'jiong2', 'jiong3', 'jiong4', 'jiong5', 'jiou1', 'jiou2', 'jiou3', 'jiou4', 'jiou5', 'jv1', 'jv2', 'jv3', 'jv4', 'jv5', 'jvan1', 'jvan2', 'jvan3', 'jvan4', 'jvan5', 'jve1', 'jve2', 'jve3', 'jve4', 'jve5', 'jvn1', 'jvn2', 'jvn3', 'jvn4', 'jvn5', 'ka1', 'ka2', 'ka3', 'ka4', 'ka5', 'kai1', 'kai2', 'kai3', 'kai4', 'kai5', 'kan1', 'kan2', 'kan3', 'kan4', 'kan5', 'kang1', 'kang2', 'kang3', 'kang4', 'kang5', 'kao1', 'kao2', 'kao3', 'kao4', 'kao5', 'ke1', 'ke2', 'ke3', 'ke4', 'ke5', 'kei1', 'kei2', 'kei3', 'kei4', 'kei5', 'ken1', 'ken2', 'ken3', 'ken4', 'ken5', 'keng1', 'keng2', 'keng3', 'keng4', 'keng5', 'kong1', 'kong2', 'kong3', 'kong4', 'kong5', 'kou1', 'kou2', 'kou3', 'kou4', 'kou5', 'ku1', 'ku2', 'ku3', 'ku4', 'ku5', 'kua1', 'kua2', 'kua3', 'kua4', 'kua5', 'kuai1', 'kuai2', 'kuai3', 'kuai4', 'kuai5', 'kuan1', 'kuan2', 'kuan3', 'kuan4', 'kuan5', 'kuang1', 'kuang2', 'kuang3', 'kuang4', 'kuang5', 'kuei1', 'kuei2', 'kuei3', 'kuei4', 'kuei5', 'kuen1', 'kuen2', 'kuen3', 'kuen4', 'kuen5', 'kuo1', 'kuo2', 'kuo3', 'kuo4', 'kuo5', 'la1', 'la2', 'la3', 'la4', 'la5', 'lai1', 'lai2', 'lai3', 'lai4', 'lai5', 'lan1', 'lan2', 'lan3', 'lan4', 'lan5', 'lang1', 'lang2', 'lang3', 'lang4', 'lang5', 'lao1', 'lao2', 'lao3', 'lao4', 'lao5', 'le1', 'le2', 'le3', 'le4', 'le5', 'lei1', 'lei2', 'lei3', 'lei4', 'lei5', 'leng1', 'leng2', 'leng3', 'leng4', 'leng5', 'li1', 'li2', 'li3', 'li4', 'li5', 'lia1', 'lia2', 'lia3', 'lia4', 'lia5', 'lian1', 'lian2', 'lian3', 'lian4', 'lian5', 'liang1', 'liang2', 'liang3', 'liang4', 'liang5', 'liao1', 'liao2', 'liao3', 'liao4', 'liao5', 'lie1', 'lie2', 'lie3', 'lie4', 'lie5', 'lin1', 'lin2', 'lin3', 'lin4', 'lin5', 'ling1', 'ling2', 'ling3', 'ling4', 'ling5', 'liou1', 'liou2', 'liou3', 'liou4', 'liou5', 'lo1', 'lo2', 'lo3', 'lo4', 'lo5', 'long1', 'long2', 'long3', 'long4', 'long5', 'lou1', 'lou2', 'lou3', 'lou4', 'lou5', 'lu1', 'lu2', 'lu3', 'lu4', 'lu5', 'luan1', 'luan2', 'luan3', 'luan4', 'luan5', 'lve1', 'lve2', 'lve3', 'lve4', 'lve5', 'lve1', 'lve2', 'lve3', 'lve4', 'lve5', 'luen1', 'luen2', 'luen3', 'luen4', 'luen5', 'luo1', 'luo2', 'luo3', 'luo4', 'luo5', 'lv1', 'lv2', 'lv3', 'lv4', 'lv5', 'ma1', 'ma2', 'ma3', 'ma4', 'ma5', 'mai1', 'mai2', 'mai3', 'mai4', 'mai5', 'man1', 'man2', 'man3', 'man4', 'man5', 'mang1', 'mang2', 'mang3', 'mang4', 'mang5', 'mao1', 'mao2', 'mao3', 'mao4', 'mao5', 'me1', 'me2', 'me3', 'me4', 'me5', 'mei1', 'mei2', 'mei3', 'mei4', 'mei5', 'men1', 'men2', 'men3', 'men4', 'men5', 'meng1', 'meng2', 'meng3', 'meng4', 'meng5', 'mi1', 'mi2', 'mi3', 'mi4', 'mi5', 'mian1', 'mian2', 'mian3', 'mian4', 'mian5', 'miao1', 'miao2', 'miao3', 'miao4', 'miao5', 'mie1', 'mie2', 'mie3', 'mie4', 'mie5', 'min1', 'min2', 'min3', 'min4', 'min5', 'ming1', 'ming2', 'ming3', 'ming4', 'ming5', 'miou1', 'miou2', 'miou3', 'miou4', 'miou5', 'mo1', 'mo2', 'mo3', 'mo4', 'mo5', 'mou1', 'mou2', 'mou3', 'mou4', 'mou5', 'mu1', 'mu2', 'mu3', 'mu4', 'mu5', 'na1', 'na2', 'na3', 'na4', 'na5', 'nai1', 'nai2', 'nai3', 'nai4', 'nai5', 'nan1', 'nan2', 'nan3', 'nan4', 'nan5', 'nang1', 'nang2', 'nang3', 'nang4', 'nang5', 'nao1', 'nao2', 'nao3', 'nao4', 'nao5', 'ne1', 'ne2', 'ne3', 'ne4', 'ne5', 'nei1', 'nei2', 'nei3', 'nei4', 'nei5', 'nen1', 'nen2', 'nen3', 'nen4', 'nen5', 'neng1', 'neng2', 'neng3', 'neng4', 'neng5', 'ni1', 'ni2', 'ni3', 'ni4', 'ni5', 'nian1', 'nian2', 'nian3', 'nian4', 'nian5', 'niang1', 'niang2', 'niang3', 'niang4', 'niang5', 'niao1', 'niao2', 'niao3', 'niao4', 'niao5', 'nie1', 'nie2', 'nie3', 'nie4', 'nie5', 'nin1', 'nin2', 'nin3', 'nin4', 'nin5', 'ning1', 'ning2', 'ning3', 'ning4', 'ning5', 'niou1', 'niou2', 'niou3', 'niou4', 'niou5', 'nong1', 'nong2', 'nong3', 'nong4', 'nong5', 'nou1', 'nou2', 'nou3', 'nou4', 'nou5', 'nu1', 'nu2', 'nu3', 'nu4', 'nu5', 'nuan1', 'nuan2', 'nuan3', 'nuan4', 'nuan5', 'nve1', 'nve2', 'nve3', 'nve4', 'nve5', 'nve1', 'nve2', 'nve3', 'nve4', 'nve5', 'nuo1', 'nuo2', 'nuo3', 'nuo4', 'nuo5', 'nv1', 'nv2', 'nv3', 'nv4', 'nv5', 'o1', 'o2', 'o3', 'o4', 'o5', 'ou1', 'ou2', 'ou3', 'ou4', 'ou5', 'pa1', 'pa2', 'pa3', 'pa4', 'pa5', 'pai1', 'pai2', 'pai3', 'pai4', 'pai5', 'pan1', 'pan2', 'pan3', 'pan4', 'pan5', 'pang1', 'pang2', 'pang3', 'pang4', 'pang5', 'pao1', 'pao2', 'pao3', 'pao4', 'pao5', 'pei1', 'pei2', 'pei3', 'pei4', 'pei5', 'pen1', 'pen2', 'pen3', 'pen4', 'pen5', 'peng1', 'peng2', 'peng3', 'peng4', 'peng5', 'pi1', 'pi2', 'pi3', 'pi4', 'pi5', 'pian1', 'pian2', 'pian3', 'pian4', 'pian5', 'piao1', 'piao2', 'piao3', 'piao4', 'piao5', 'pie1', 'pie2', 'pie3', 'pie4', 'pie5', 'pin1', 'pin2', 'pin3', 'pin4', 'pin5', 'ping1', 'ping2', 'ping3', 'ping4', 'ping5', 'po1', 'po2', 'po3', 'po4', 'po5', 'pou1', 'pou2', 'pou3', 'pou4', 'pou5', 'pu1', 'pu2', 'pu3', 'pu4', 'pu5', 'qi1', 'qi2', 'qi3', 'qi4', 'qi5', 'qia1', 'qia2', 'qia3', 'qia4', 'qia5', 'qian1', 'qian2', 'qian3', 'qian4', 'qian5', 'qiang1', 'qiang2', 'qiang3', 'qiang4', 'qiang5', 'qiao1', 'qiao2', 'qiao3', 'qiao4', 'qiao5', 'qie1', 'qie2', 'qie3', 'qie4', 'qie5', 'qin1', 'qin2', 'qin3', 'qin4', 'qin5', 'qing1', 'qing2', 'qing3', 'qing4', 'qing5', 'qiong1', 'qiong2', 'qiong3', 'qiong4', 'qiong5', 'qiou1', 'qiou2', 'qiou3', 'qiou4', 'qiou5', 'qv1', 'qv2', 'qv3', 'qv4', 'qv5', 'qvan1', 'qvan2', 'qvan3', 'qvan4', 'qvan5', 'qve1', 'qve2', 'qve3', 'qve4', 'qve5', 'qvn1', 'qvn2', 'qvn3', 'qvn4', 'qvn5', 'ran1', 'ran2', 'ran3', 'ran4', 'ran5', 'rang1', 'rang2', 'rang3', 'rang4', 'rang5', 'rao1', 'rao2', 'rao3', 'rao4', 'rao5', 're1', 're2', 're3', 're4', 're5', 'ren1', 'ren2', 'ren3', 'ren4', 'ren5', 'reng1', 'reng2', 'reng3', 'reng4', 'reng5', 'riii1', 'riii2', 'riii3', 'riii4', 'riii5', 'rong1', 'rong2', 'rong3', 'rong4', 'rong5', 'rou1', 'rou2', 'rou3', 'rou4', 'rou5', 'ru1', 'ru2', 'ru3', 'ru4', 'ru5', 'rua1', 'rua2', 'rua3', 'rua4', 'rua5', 'ruan1', 'ruan2', 'ruan3', 'ruan4', 'ruan5', 'ruei1', 'ruei2', 'ruei3', 'ruei4', 'ruei5', 'ruen1', 'ruen2', 'ruen3', 'ruen4', 'ruen5', 'ruo1', 'ruo2', 'ruo3', 'ruo4', 'ruo5', 'sa1', 'sa2', 'sa3', 'sa4', 'sa5', 'sai1', 'sai2', 'sai3', 'sai4', 'sai5', 'san1', 'san2', 'san3', 'san4', 'san5', 'sang1', 'sang2', 'sang3', 'sang4', 'sang5', 'sao1', 'sao2', 'sao3', 'sao4', 'sao5', 'se1', 'se2', 'se3', 'se4', 'se5', 'sen1', 'sen2', 'sen3', 'sen4', 'sen5', 'seng1', 'seng2', 'seng3', 'seng4', 'seng5', 'sha1', 'sha2', 'sha3', 'sha4', 'sha5', 'shai1', 'shai2', 'shai3', 'shai4', 'shai5', 'shan1', 'shan2', 'shan3', 'shan4', 'shan5', 'shang1', 'shang2', 'shang3', 'shang4', 'shang5', 'shao1', 'shao2', 'shao3', 'shao4', 'shao5', 'she1', 'she2', 'she3', 'she4', 'she5', 'shei1', 'shei2', 'shei3', 'shei4', 'shei5', 'shen1', 'shen2', 'shen3', 'shen4', 'shen5', 'sheng1', 'sheng2', 'sheng3', 'sheng4', 'sheng5', 'shiii1', 'shiii2', 'shiii3', 'shiii4', 'shiii5', 'shou1', 'shou2', 'shou3', 'shou4', 'shou5', 'shu1', 'shu2', 'shu3', 'shu4', 'shu5', 'shua1', 'shua2', 'shua3', 'shua4', 'shua5', 'shuai1', 'shuai2', 'shuai3', 'shuai4', 'shuai5', 'shuan1', 'shuan2', 'shuan3', 'shuan4', 'shuan5', 'shuang1', 'shuang2', 'shuang3', 'shuang4', 'shuang5', 'shuei1', 'shuei2', 'shuei3', 'shuei4', 'shuei5', 'shuen1', 'shuen2', 'shuen3', 'shuen4', 'shuen5', 'shuo1', 'shuo2', 'shuo3', 'shuo4', 'shuo5', 'sii1', 'sii2', 'sii3', 'sii4', 'sii5', 'song1', 'song2', 'song3', 'song4', 'song5', 'sou1', 'sou2', 'sou3', 'sou4', 'sou5', 'su1', 'su2', 'su3', 'su4', 'su5', 'suan1', 'suan2', 'suan3', 'suan4', 'suan5', 'suei1', 'suei2', 'suei3', 'suei4', 'suei5', 'suen1', 'suen2', 'suen3', 'suen4', 'suen5', 'suo1', 'suo2', 'suo3', 'suo4', 'suo5', 'ta1', 'ta2', 'ta3', 'ta4', 'ta5', 'tai1', 'tai2', 'tai3', 'tai4', 'tai5', 'tan1', 'tan2', 'tan3', 'tan4', 'tan5', 'tang1', 'tang2', 'tang3', 'tang4', 'tang5', 'tao1', 'tao2', 'tao3', 'tao4', 'tao5', 'te1', 'te2', 'te3', 'te4', 'te5', 'tei1', 'tei2', 'tei3', 'tei4', 'tei5', 'teng1', 'teng2', 'teng3', 'teng4', 'teng5', 'ti1', 'ti2', 'ti3', 'ti4', 'ti5', 'tian1', 'tian2', 'tian3', 'tian4', 'tian5', 'tiao1', 'tiao2', 'tiao3', 'tiao4', 'tiao5', 'tie1', 'tie2', 'tie3', 'tie4', 'tie5', 'ting1', 'ting2', 'ting3', 'ting4', 'ting5', 'tong1', 'tong2', 'tong3', 'tong4', 'tong5', 'tou1', 'tou2', 'tou3', 'tou4', 'tou5', 'tu1', 'tu2', 'tu3', 'tu4', 'tu5', 'tuan1', 'tuan2', 'tuan3', 'tuan4', 'tuan5', 'tuei1', 'tuei2', 'tuei3', 'tuei4', 'tuei5', 'tuen1', 'tuen2', 'tuen3', 'tuen4', 'tuen5', 'tuo1', 'tuo2', 'tuo3', 'tuo4', 'tuo5', 'wua1', 'wua2', 'wua3', 'wua4', 'wua5', 'wuai1', 'wuai2', 'wuai3', 'wuai4', 'wuai5', 'wuan1', 'wuan2', 'wuan3', 'wuan4', 'wuan5', 'wuang1', 'wuang2', 'wuang3', 'wuang4', 'wuang5', 'wuei1', 'wuei2', 'wuei3', 'wuei4', 'wuei5', 'wuen1', 'wuen2', 'wuen3', 'wuen4', 'wuen5', 'wuen1', 'wuen2', 'wuen3', 'wuen4', 'wuen5', 'wuo1', 'wuo2', 'wuo3', 'wuo4', 'wuo5', 'wu1', 'wu2', 'wu3', 'wu4', 'wu5', 'xi1', 'xi2', 'xi3', 'xi4', 'xi5', 'xia1', 'xia2', 'xia3', 'xia4', 'xia5', 'xian1', 'xian2', 'xian3', 'xian4', 'xian5', 'xiang1', 'xiang2', 'xiang3', 'xiang4', 'xiang5', 'xiao1', 'xiao2', 'xiao3', 'xiao4', 'xiao5', 'xie1', 'xie2', 'xie3', 'xie4', 'xie5', 'xin1', 'xin2', 'xin3', 'xin4', 'xin5', 'xing1', 'xing2', 'xing3', 'xing4', 'xing5', 'xiong1', 'xiong2', 'xiong3', 'xiong4', 'xiong5', 'xiou1', 'xiou2', 'xiou3', 'xiou4', 'xiou5', 'xv1', 'xv2', 'xv3', 'xv4', 'xv5', 'xvan1', 'xvan2', 'xvan3', 'xvan4', 'xvan5', 'xve1', 'xve2', 'xve3', 'xve4', 'xve5', 'xvn1', 'xvn2', 'xvn3', 'xvn4', 'xvn5', 'yia1', 'yia2', 'yia3', 'yia4', 'yia5', 'yian1', 'yian2', 'yian3', 'yian4', 'yian5', 'yiang1', 'yiang2', 'yiang3', 'yiang4', 'yiang5', 'yiao1', 'yiao2', 'yiao3', 'yiao4', 'yiao5', 'yie1', 'yie2', 'yie3', 'yie4', 'yie5', 'yi1', 'yi2', 'yi3', 'yi4', 'yi5', 'yin1', 'yin2', 'yin3', 'yin4', 'yin5', 'ying1', 'ying2', 'ying3', 'ying4', 'ying5', 'yiou1', 'yiou2', 'yiou3', 'yiou4', 'yiou5', 'yiong1', 'yiong2', 'yiong3', 'yiong4', 'yiong5', 'yiou1', 'yiou2', 'yiou3', 'yiou4', 'yiou5', 'yv1', 'yv2', 'yv3', 'yv4', 'yv5', 'yvan1', 'yvan2', 'yvan3', 'yvan4', 'yvan5', 'yve1', 'yve2', 'yve3', 'yve4', 'yve5', 'yvn1', 'yvn2', 'yvn3', 'yvn4', 'yvn5', 'za1', 'za2', 'za3', 'za4', 'za5', 'zai1', 'zai2', 'zai3', 'zai4', 'zai5', 'zan1', 'zan2', 'zan3', 'zan4', 'zan5', 'zang1', 'zang2', 'zang3', 'zang4', 'zang5', 'zao1', 'zao2', 'zao3', 'zao4', 'zao5', 'ze1', 'ze2', 'ze3', 'ze4', 'ze5', 'zei1', 'zei2', 'zei3', 'zei4', 'zei5', 'zen1', 'zen2', 'zen3', 'zen4', 'zen5', 'zeng1', 'zeng2', 'zeng3', 'zeng4', 'zeng5', 'zha1', 'zha2', 'zha3', 'zha4', 'zha5', 'zhai1', 'zhai2', 'zhai3', 'zhai4', 'zhai5', 'zhan1', 'zhan2', 'zhan3', 'zhan4', 'zhan5', 'zhang1', 'zhang2', 'zhang3', 'zhang4', 'zhang5', 'zhao1', 'zhao2', 'zhao3', 'zhao4', 'zhao5', 'zhe1', 'zhe2', 'zhe3', 'zhe4', 'zhe5', 'zhei1', 'zhei2', 'zhei3', 'zhei4', 'zhei5', 'zhen1', 'zhen2', 'zhen3', 'zhen4', 'zhen5', 'zheng1', 'zheng2', 'zheng3', 'zheng4', 'zheng5', 'zhiii1', 'zhiii2', 'zhiii3', 'zhiii4', 'zhiii5', 'zhong1', 'zhong2', 'zhong3', 'zhong4', 'zhong5', 'zhou1', 'zhou2', 'zhou3', 'zhou4', 'zhou5', 'zhu1', 'zhu2', 'zhu3', 'zhu4', 'zhu5', 'zhua1', 'zhua2', 'zhua3', 'zhua4', 'zhua5', 'zhuai1', 'zhuai2', 'zhuai3', 'zhuai4', 'zhuai5', 'zhuan1', 'zhuan2', 'zhuan3', 'zhuan4', 'zhuan5', 'zhuang1', 'zhuang2', 'zhuang3', 'zhuang4', 'zhuang5', 'zhuei1', 'zhuei2', 'zhuei3', 'zhuei4', 'zhuei5', 'zhuen1', 'zhuen2', 'zhuen3', 'zhuen4', 'zhuen5', 'zhuo1', 'zhuo2', 'zhuo3', 'zhuo4', 'zhuo5', 'zii1', 'zii2', 'zii3', 'zii4', 'zii5', 'zong1', 'zong2', 'zong3', 'zong4', 'zong5', 'zou1', 'zou2', 'zou3', 'zou4', 'zou5', 'zu1', 'zu2', 'zu3', 'zu4', 'zu5', 'zuan1', 'zuan2', 'zuan3', 'zuan4', 'zuan5', 'zuei1', 'zuei2', 'zuei3', 'zuei4', 'zuei5', 'zuen1', 'zuen2', 'zuen3', 'zuen4', 'zuen5', 'zuo1', 'zuo2', 'zuo3', 'zuo4', 'zuo5']
是一样的？

**Comment by cnlinxi** [comment]
输入音素，如拼音字母的“a”，“b”等，不是一个汉字对应的拼音。
