### ISSUE TITLE
question

### ISSUE THREAD

**Issue by szm19931109** [cnlinxi/tacotron2#2]
你好：
         这是你那篇《一种基于 Ｔａｃ ｏｔ ｒｏｎ ２ 的 端到 端 中 文语音合成方案》论文的源码吗？

**Comment by cnlinxi** [comment]
这个代码不完全是。这个repo是之前学习tacotron2时的一个repo而已。

**Comment by szm19931109** [comment]
你的源码能开源码

**Comment by cnlinxi** [comment]
> 你的源码能开源码

会的，我会在完成我的大论文后公开这些源代码的～

**Comment by szm19931109** [comment]
那最迟什么时间呢  ，我很期待

**Comment by cnlinxi** [comment]
> 那最迟什么时间呢 ，我很期待

谢谢你的关注。事实上关于中文tts，我之后还有很多有意思的发现。但是有一些是实习期间完成的，虽然我早已离职，但是我不是很确定公开源码会不会损害公司的利益，所以我想要和一些人协商以后才能公开源代码，我会尽快的～

**Comment by szm19931109** [comment]
加个微信吧&nbsp; 老铁








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cnlinxi"<notifications@github.com&gt;; 
发送时间: 2019年10月8日(星期二) 下午5:09
收件人: "cnlinxi/tacotron2"<tacotron2@noreply.github.com&gt;; 
抄送: "风浪"<805484734@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [cnlinxi/tacotron2] question (#2)



 
那最迟什么时间呢 ，我很期待
  
谢谢你的关注。事实上关于中文tts，我之后还有很多有意思的发现。但是有一些是实习期间完成的，虽然我早已离职，但是我不是很确定公开源码会不会损害公司的利益，所以我想要和一些人协商以后才能公开源代码，我会尽快的～

**Comment by cnlinxi** [comment]
> 加个微信吧&nbsp; 老铁

我的微信昨天直接回复那个通知邮件了，但是我不是很确定你能收得到，我不好在这里展示我的微信号
